---
- hosts: all
  gather_facts: no
  tasks:
    - name: Stop all services
      docker_compose:
        project_src: "/var/lib/awx/build_image/"
        build: no
        stopped: yes
      register: output