---
- hosts: all
  gather_facts: no
  tasks:
    - name: Disable firewall
      systemd:
        name: firewalld.service
        state: stopped
        enabled: no

    - name: Add Docker-CE yum repository
      yum_repository:
        name: Docker-CE
        file: docker-ce
        description: docker-ce-stable
        baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
        enabled: yes
        gpgcheck: yes
        gpgkey: https://download.docker.com/linux/centos/gpg
    
    - name: Install the dependencies
      yum:
        name: "{{ packages }}"
        update_cache: yes
      vars:
        packages:
        - gcc
        - python3-devel
        - python3-pip
        - python-setuptools
        - docker-ce
      
    - name: Install the docker-py libraries
      pip:
        name: 
          - docker-compose==1.24.0
        executable: pip3

    - name: Enable Docker services
      systemd:
        name: docker.service
        state: started
        enabled: yes